services:
  - type: web
    name: home-services-backend
    env: docker
    plan: free
    dockerCommand: sh ./start.sh
    envVars:
      - key: APP_KEY
        value: "base64:HIQDUtNCPl1jrsWHn23evkuQwbGRYtnjYvUomwzdy4c="
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: CACHE_STORE
        value: file
      - key: REVERB_APP_ID
        value: 829314
      - key: REVERB_APP_KEY
        value: 7d8f921e3b6a4c59
      - key: REVERB_APP_SECRET
        value: f4a8b2c1d9e3f7a6b5c4d3e2f1a0b9c8
      - key: REVERB_HOST
        value: home-services-reverb.onrender.com
      - key: REVERB_PORT
        value: 443
      - key: REVERB_SCHEME
        value: https

  - type: web
    name: home-services-reverb
    env: docker
    plan: free
    dockerCommand: sh ./start-reverb.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: REVERB_APP_ID
        value: 829314
      - key: REVERB_APP_KEY
        value: 7d8f921e3b6a4c59
      - key: REVERB_APP_SECRET
        value: f4a8b2c1d9e3f7a6b5c4d3e2f1a0b9c8
